// Mock restaurant data for fallback when Supabase is not configured
export const mockRestaurants = [
    {
        id: '1',
        name: 'The Golden Fork',
        description: 'Fine dining experience with exquisite French cuisine in an elegant setting. Our award-winning chef brings the best of Paris to your plate.',
        image_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop',
        location: 'Downtown, New York',
        address: '123 5th Avenue, New York, NY 10001',
        category: 'Fine Dining',
        cuisine: 'French',
        price_range: '$$$',
        phone: '+1 (212) 555-0101',
        website: 'https://goldenfork.example.com',
        hours: 'Mon-Sun: 12pm - 11pm',
        avg_rating: 4.8,
        total_reviews: 124,
        featured: true,
    },
    {
        id: '2',
        name: 'Spice Garden',
        description: 'Authentic Indian cuisine with bold flavors and vibrant spices. Experience the rich tapestry of Indian cooking traditions.',
        image_url: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&auto=format&fit=crop',
        location: 'Midtown, New York',
        address: '456 Madison Ave, New York, NY 10022',
        category: 'Restaurant',
        cuisine: 'Indian',
        price_range: '$$',
        phone: '+1 (212) 555-0202',
        hours: 'Tue-Sun: 11am - 10pm',
        avg_rating: 4.6,
        total_reviews: 89,
        featured: true,
    },
    {
        id: '3',
        name: 'The Burger Lab',
        description: 'Gourmet burgers crafted with premium ingredients and house-made secret sauces. Bold flavors, massive portions.',
        image_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop',
        location: 'Brooklyn, New York',
        address: '789 Bedford Ave, Brooklyn, NY 11211',
        category: 'Casual',
        cuisine: 'American',
        price_range: '$',
        phone: '+1 (718) 555-0303',
        hours: 'Mon-Sun: 11am - 1am',
        avg_rating: 4.5,
        total_reviews: 210,
        featured: true,
    },
    {
        id: '4',
        name: 'Sakura Sushi',
        description: 'Traditional Japanese sushi and sashimi made with the freshest fish by master chefs trained in Osaka.',
        image_url: 'https://images.unsplash.com/photo-1611143669185-af224c5e3252?w=800&auto=format&fit=crop',
        location: 'Upper East Side, New York',
        address: '321 Lexington Ave, New York, NY 10016',
        category: 'Restaurant',
        cuisine: 'Japanese',
        price_range: '$$$',
        phone: '+1 (212) 555-0404',
        hours: 'Mon-Sat: 12pm - 10:30pm',
        avg_rating: 4.9,
        total_reviews: 176,
        featured: true,
    },
    {
        id: '5',
        name: 'La Piazza',
        description: 'Rustic Italian trattoria serving homemade pasta and wood-fired pizza just like Nonna used to make in Rome.',
        image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop',
        location: 'Little Italy, New York',
        address: '15 Mulberry St, New York, NY 10013',
        category: 'Restaurant',
        cuisine: 'Italian',
        price_range: '$$',
        phone: '+1 (212) 555-0505',
        hours: 'Tue-Sun: 12pm - 11pm',
        avg_rating: 4.7,
        total_reviews: 143,
        featured: false,
    },
    {
        id: '6',
        name: 'Ocean Blue',
        description: 'Fresh seafood caught daily in a nautical-themed atmosphere. Lobster, shrimp, and seasonal catches prepared to perfection.',
        image_url: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&auto=format&fit=crop',
        location: 'Harbor District, New York',
        address: '88 South Street, New York, NY 10038',
        category: 'Seafood',
        cuisine: 'American',
        price_range: '$$$',
        phone: '+1 (212) 555-0606',
        hours: 'Wed-Mon: 11am - 10pm',
        avg_rating: 4.4,
        total_reviews: 97,
        featured: false,
    },
    {
        id: '7',
        name: 'Taco Loco',
        description: 'Authentic Mexican street food with bold flavors, fresh ingredients, and a lively atmosphere you will love.',
        image_url: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&auto=format&fit=crop',
        location: 'East Village, New York',
        address: '201 Ave A, New York, NY 10009',
        category: 'Casual',
        cuisine: 'Mexican',
        price_range: '$',
        phone: '+1 (212) 555-0707',
        hours: 'Mon-Sun: 10am - 12am',
        avg_rating: 4.3,
        total_reviews: 158,
        featured: false,
    },
    {
        id: '8',
        name: 'The Rooftop Cafe',
        description: 'Stunning skyline views paired with modern American cuisine. An unforgettable dining experience high above the city.',
        image_url: 'https://images.unsplash.com/photo-1592861956120-e524fc739696?w=800&auto=format&fit=crop',
        location: 'Manhattan, New York',
        address: '500 W 48th St, New York, NY 10036',
        category: 'Cafe',
        cuisine: 'American',
        price_range: '$$',
        phone: '+1 (212) 555-0808',
        hours: 'Fri-Sun: 4pm - 11pm',
        avg_rating: 4.6,
        total_reviews: 112,
        featured: true,
    },
]

export const mockReviews = [
    { id: 'r1', restaurant_id: '1', rating: 5, comment: 'Absolutely outstanding! The best French food I have had outside of Paris.', created_at: '2024-01-15T10:00:00Z', profiles: { name: 'Sarah M.', avatar_url: null } },
    { id: 'r2', restaurant_id: '1', rating: 4, comment: 'Excellent food and ambiance. A bit pricey but worth every penny.', created_at: '2024-01-10T10:00:00Z', profiles: { name: 'James K.', avatar_url: null } },
    { id: 'r3', restaurant_id: '2', rating: 5, comment: 'The butter chicken is divine! Perfectly spiced and incredibly creamy.', created_at: '2024-01-12T10:00:00Z', profiles: { name: 'Priya S.', avatar_url: null } },
    { id: 'r4', restaurant_id: '3', rating: 5, comment: 'Best burgers in NYC, hands down. The truffle fries are a must!', created_at: '2024-01-08T10:00:00Z', profiles: { name: 'Mike L.', avatar_url: null } },
]

export const categories = ['All', 'Fine Dining', 'Restaurant', 'Casual', 'Seafood', 'Cafe', 'Fast Food', 'Bakery']

export const cuisines = ['All', 'American', 'French', 'Italian', 'Japanese', 'Indian', 'Mexican', 'Chinese', 'Thai', 'Greek']
